main/blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('', views.blog, name="blog"),
    path('<slug:slug>/', views.post, name="post"),
]

main/main/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from .sitemap import PostSitemap, ShopCategory, ShopProduct

sitemaps = {
    'posts': PostSitemap,
    'category': ShopCategory,
    'products': ShopProduct,
}

from main import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('about/', include('home.urls')),
    path('category/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('service/', include('service.urls')),
    path('user/', include('users.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('admin/', include('admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),  # Маршрут для sitemap.xml
    path('', include('home.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    path('', views.order, name="order"),
    path('create/', views.order_create, name="order_create"), 
    path('order-succes/', views.order_succes, name="order_succes"), 
    path('order-error/', views.order_error, name='order_error'),
    path('success/', views.order_success, name='order_success'),
    # path('cart_change/', views.cart_change, name="cart_change"), 
    # path('cart_remove/', views.cart_remove, name="cart_remove"), 
]

main/order/models.py
from django.db import models
from shop.models import Product

from users.models import User

class OrderItemQuerySet(models.QuerySet):
  
  def total_price(self):
    return sum(cart.products_price() for cart in self)
  
  def total_quantity(self):
    if self:
      return sum(cart.quantity for cart in self)
    return 0

class Order(models.Model):
  user = models.ForeignKey(User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None, verbose_name="Пользователь")
  first_name = models.CharField(max_length=50, null=True, blank=True, verbose_name='Имя')
  email = models.EmailField(null=True, blank=True, verbose_name='E-mail')
  created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
  phone = models.CharField(max_length=50, default=True, null=True, blank=True, verbose_name="Номер телефона")
  requires_delivery = models.BooleanField(null=True, blank=True, verbose_name="Нужна доставка ?")
  delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
  payment_id = models.CharField(max_length=250, verbose_name="ID платежа", null=True, blank=True)
  payment_dop_info = models.CharField(max_length=550, verbose_name="Информация о платеже (ссылка на плптеж)", null=True, blank=True)
  pay_method = models.CharField(max_length=250, verbose_name="Способ оплаты", null=True, blank=True)
  is_paid = models.BooleanField(default=False, verbose_name="Оплачено ?")
  summ = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name="Общая сумма платежа")
  anonymous =  models.BooleanField(default=False, verbose_name="Не говорить от кого")
  surprise =  models.BooleanField(default=False, verbose_name="Не предупреждать получателя")
  first_name_human = models.CharField(max_length=250, null=True, blank=True, verbose_name="Имя получателя")
  phone_number_human = models.CharField(max_length=50, null=True, blank=True, verbose_name="Номер получателя")
  pickup = models.BooleanField(default=False, verbose_name="Самовывоз")
  who_get_bouqets = models.BooleanField(default=False, verbose_name="Кто получатель ?")
  
  ORDER_STATUS = (
    ('Новый', 'Новый'),
    ('В работе', 'В работе'),
    ('Обработан', 'Обработан'),
    ('Выполнен', 'Выполнен'),
    ('Отказ', 'Отказ')
  )
  models.CharField(max_length=250, verbose_name='Статус заказа', choices=ORDER_STATUS, default='Новый',)
  
  class Meta:
    db_table="order"
    verbose_name="Заказ"
    verbose_name_plural="Заказы"
    
  def __str__(self) :
    return f"Заказа № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
  
class OrderItem(models.Model):
  order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items", verbose_name="Заказ")
  product = models.ForeignKey(Product, on_delete=models.SET_DEFAULT, default=None, blank=True, null=True, verbose_name="Продукт")
  name = models.CharField(max_length=150, verbose_name="Имя товара")
  price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
  quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
  created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")
  selected_char = models.JSONField(default=dict)
  
  class Meta:
    db_table = "order_item"
    verbose_name = "Проданный товара"
    verbose_name_plural = "Проданные товары"
    
  objects = OrderItemQuerySet().as_manager()
  
  """Суммарная цена продуктов(обащая цена)"""  
  def products_price(self):
    return round(self.sell_price() * self.quantity, 2)
  
  def __str__(self):
    return f"Товар {self.name} | Заказ № {self.pk}"
  
  

main/order/forms.py
from django import forms

from order.models import Order


# class CreateOrderForm(forms.Form):
#   # RESIPIENT_CHOICE = (
#   #   ("myself", "Я сам"),
#   #   ("another-man", "Другой человек"),
#   # )
#   # who_get_bouqets = forms.ChoiceField(widget=forms.RadioSelect, choices=RESIPIENT_CHOICE, required=False)
#   first_name = forms.CharField(required=False)
#   last_name = forms.CharField(required=False)
#   email = forms.CharField(required=False)
#   phone_number = forms.CharField(required=False)
#   first_name_human = forms.CharField(required=False)
#   phone_number_human = forms.CharField(required=False)
#   surprise = forms.CharField(required=False)
#   anonymous = forms.CharField(required=False)
#   delivery_address = forms.CharField(required=False)

class CreateOrderForm(forms.ModelForm):
   class Meta:
      model = Order
      fields = ['first_name', 'phone', 'email', 'delivery_address']

main/order/views.py
from django.db import transaction
from django.forms import ValidationError
from django.contrib import messages
from django.shortcuts import redirect, render
from cart.models import Cart
from payment.alfabank import create_payment, get_status
from .email_send import email_send
from order.models import Order, OrderItem
from order.forms import CreateOrderForm
from django.contrib.auth.decorators import login_required

def order(request):
  ...

def order_create(request):
  form = CreateOrderForm(request.POST)
  
  
  if request.method == "POST":
    if form.is_valid():
      
      """
        Получаем способ оплаты и в зависимости от 
        метода оплаты строим логику ниже
      """
      payment_method = None
      try:
        order = form.save(commit=False)
        if request.user.is_authenticated:
          user = request.user
          order.user = user
          # Получаем корзину пользователя если он авторизован
        else:
          order.user = None
          # Получаем корзину пользователя если он не авторизован по ключу сессии
          session_key = request.session.session_key
          cart_items = Cart.objects.filter(session_key=session_key)
          
          try: 
            first_name = request.POST['first_name']
            order.first_name = first_name
          except:
            pass
          
          try:
            email = request.POST['email']
            order.email = email
          except:
            pass
          
          try:
            first_name_human = request.POST['first_name_human']
            order.first_name_human = first_name_human
          except:
            pass
          
          try:
            phone_number_human = request.POST['phone_number_human']
            order.phone_number_human = phone_number_human
          except:
            pass
          
          try:
            pickup = request.POST['pickup']
            order.pickup = True
          except:
            pass
          
          try:
            surprise = request.POST['surprise']
            order.surprise = True
          except:
            pass
          
          try:
            anonymous = request.POST['anonymous']
            order.anonymous = True
          except:
            pass
          
          try:
            phone = request.POST['phone']
            order.phone = phone
          except:
            pass
          
          try:
            delivery_address = request.POST['delivery_address']
            order.delivery_address = delivery_address
          except: 
            pass
          
          try:
            pay_method = request.POST['payment_option']
            order.pay_method = pay_method
          except: 
            pay_method = None
          
          order.save()
        
          for item in cart_items:
            product=item.product
            name=item.product.name
            price=item.product.price
            quantity=item.quantity
            selected_char=item.selected_char
            
            orderItem  = OrderItem.objects.create(
              order = order,
              product=product,
              name=name,
              price=price,
              quantity=quantity,
              selected_char=selected_char
            )
          
          if payment_method == "На сайте картой":
              data = create_payment(orderItem, cart_items, request)
              payment_id = data["id"]
              confirmation_url = data["confirmation_url"]

              order.payment_id = payment_id
              order.payment_dop_info = confirmation_url
              order.save()
              cart_items.delete()
              return redirect(confirmation_url)
          else:
            email_send(order)
            cart_items.delete()
            return redirect('order_succes')
      except Exception as e:
        print(e)
    else:
      print(form)

  session_key = request.session.session_key
  cart_items = Cart.objects.filter(session_key=session_key)
  
  context = {
    'title': 'Оформление заказа',
    'orders': True,
    "cart": cart_items
  }
      
  return render(request, "pages/orders/create.html", context)

def order_error(request):
    return render(request, "pages/orders/error.html")

def order_success(request):
    session_key = request.session.session_key
    cart = Cart.objects.filter(session_key=session_key)

    pay_id = request.GET["orderId"]

    data = get_status(pay_id)

    if data["status"] == "0":
        order = data["order"]

        email_send(order)

        text = f"Ваш заказ принят. Ему присвоен № {order.id}."

        session_key = request.session.session_key
        cart_items = Cart.objects.filter(session_key=session_key)
        request.session["delivery"] = 1
        order.paid = True

        order.save()
        
        return redirect("/?order=True")

    else:
        return redirect("order_error")

# def order_create(request):
#   if request.method == 'POST':
#     form = CreateOrderForm(data=request.POST)
#     print(request.POST["first_name"])
#     if form.is_valid():
#       try:
#         # with transaction.atomic():
#           if request.user.is_authenticated:
#             print("USer")
#             user = request.user
#             cart_items = Cart.objects.filter(user=user)

#             if cart_items.exists():
#                 # Создать заказ
#                 order = Order.objects.create(
#                     user=user,
#                     who_get_bouqets = form.cleaned_data['who-get-bouqets'],
#                     first_name = form.cleaned_data['first_name'],
#                     phone_number=form.cleaned_data['phone_number'],
#                     email=form.cleaned_data['email'],
#                     first_name_human=form.cleaned_data['first_name_human'],
#                     phone_number_human=form.cleaned_data['phone_number_human'],
#                     surprise=form.cleaned_data['surprise'],
#                     anonymous=form.cleaned_data['anonymous'],
#                     delivery_address=form.cleaned_data['delivery_address'],
#                     payment_option=form.cleaned_data['payment_option'],
#                 )
#                 print(f"{order} - заказ авторизованного")
#                 # Создать заказанные товары
#                 for cart_item in cart_items:
#                     product=cart_item.product
#                     name=cart_item.product.name
#                     price=cart_item.product.sell_price()
#                     quantity=cart_item.quantity


#                     if product.quantity < quantity:
#                         raise ValidationError(f'Недостаточное количество товара {name} на складе | В наличии - {product.quantity}')

#                     OrderItem.objects.create(
#                         order=order,
#                         product=product,
#                         name=name,
#                         price=price,
#                         quantity=quantity,
#                     )
#                     product.quantity -= quantity
#                     product.save()

#                 # Очистить корзину пользователя после создания заказа
#                 cart_items.delete()
#                 messages.success(request, 'Заказ оформлен!')
#                 return redirect('order_succes')
#           else:
#             session_key=request.session.session_key
#             cart_items = Cart.objects.filter(session_key=session_key)
#             print(cart_items)
#             if cart_items.exists():
#                 # Создать заказ
#                 order = Order.objects.create(
#                     phone_number=form.cleaned_data['phone_number'],
#                     delivery_address=form.cleaned_data['delivery_address'],
#                     payment_option=form.cleaned_data['payment_option'],
#                 )
#                 print(f"{order.id} - заказ сессии")
#                 # Создать заказанные товары
#                 for cart_item in cart_items:
#                     product=cart_item.product
#                     name=cart_item.product.name
#                     price=cart_item.product.sell_price()
#                     quantity=cart_item.quantity


#                     if product.quantity < quantity:
#                         raise ValidationError(f'Недостаточное количество товара {name} на складе | В наличии - {product.quantity}')

#                     OrderItem.objects.create(
#                         order=order,
#                         product=product,
#                         name=name,
#                         price=price,
#                         quantity=quantity,
#                     )
#                     product.quantity -= quantity
#                     product.save()

#                 # Очистить корзину пользователя после создания заказа
#                 cart_items.delete()
#                 messages.success(request, 'Заказ оформлен!')
#                 return redirect('order_succes')
#       except ValidationError as e:
#         print('2')
#         print(e)
#         messages.success(request, str(e))
#         return redirect('order_create')
#     else:
#       initial = {
#         # 'first_name': request.user.first_name,
#         'first_name': "",
#         # 'last_name': request.user.last_name,
#         'last_name': "",
#         }
#     form = CreateOrderForm(initial=initial)

#   context = {
#     'title': 'Home - Оформление заказа',
#     'form': form,
#     'orders': True,
#   }
#   return render(request, 'pages/orders/create.html', context)

def order_succes(request):
  return render(request, "pages/orders/success.html")

main/core/theme/mb/templates/pages/orders/create copy.html
{% extends "base.html" %} {% load static %}{% load thumbnail %}{% block content %}
<main>
  <section class="order-create">
    <form action="{% url 'order_create' %}" method="POST" class="form">
      <h2 class="order-create__title">Оформление заказа</h2>
      <div class="order-create__row">
        <div class="order-create__col">
          {% csrf_token %}
          <div class="form__item">
            <p class="form__item-title">Кто получит букет ?</p>
            <div class="form__boolean">
              <input type="radio" name="who_get_bouqets" class="form__controls-radio who-get" id="id_who_get_bouqets" value="Я сам" checked />
              <label for="id_who_get_bouqets" class="form__boolean-label">Я сам</label>
            </div>
            <div class="form__boolean">
              <input type="radio" name="who_get_bouqets" class="form__controls-radio who-get" id="id_another_man" value="Другой человек" data-id="another" />
              <label for="id_another_man" class="form__boolean-label">Другой человек</label>
            </div>
          </div>
          <div class="form__item">
            <p class="form__item-title">Ваши контакты</p>
            <div class="form__group-grid">
              <div class="form__group">
                <label for="id_first_name" class="form__label">Имя*:</label>
                <input
                  type="text"
                  class="form__controls"
                  id="id_first_name"
                  value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                  name="first_name"
                  required
                />
              </div>
              <div class="form__group">
                <label for="id_email" class="form__label">Email*:</label>
                <input type="text" class="form__controls" id="id_email" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required />
              </div>
              <div class="form__group">
                <label for="id_phone_number" class="form__label">Номер телефона*:</label>
                <input type="text" class="form__controls" id="id_phone_number" name="phone" value="" placeholder="В формате: XXX-XXX-XX-XX" required />
              </div>
            </div>
          </div>
          <div class="form__item" id="contact-human">
            <p class="form__item-title">Контакты получателя</p>
            <div class="form__group-grid">
              <div class="form__group">
                <label for="id_first_name_human" class="form__label">Имя<span>*</span>:</label>
                <input type="text" class="form__controls" id="id_first_name_human" value="" name="first_name_human" />
              </div>
              <div class="form__group">
                <label for="id_phone_number_human" class="form__label">Номер телефона*:</label>
                <input type="text" class="form__controls" id="id_phone_number_human" name="phone_number_human" value="" placeholder="В формате: XXX-XXX-XX-XX" />
              </div>
              <div class="form__group">
                <div class="form__group-boolean">
                  <input type="checkbox" name="surprise" id="surprise" class="form__controls-checkbox" />
                  <label for="surprise" class="form__boolean-label">Сюрприз (не предупреждать получателя)</label>
                </div>
                <div class="form__group-boolean">
                  <input type="checkbox" name="anonymous" id="anonymous" class="form__controls-checkbox" />
                  <label for="anonymous" class="form__boolean-label">Не говорить от кого</label>
                </div>
              </div>
            </div>
          </div>
          <div class="form__item">
            <p class="form__item-title">Адрес доставки</p>
            <div class="form__group-boolean">
              <input type="checkbox" name="pickup" id="pickup" class="form__controls-checkbox" checked />
              <label for="pickup" class="form__boolean-label">Самовывоз</label>
            </div>
            <div class="form__group _hidden" id="id_delivery_address">
              <input type="text" class="form__controls" name="delivery_address" />
              <span class="form__help-text">Город, улица, дом, подъезд, офис/квартира</span>
            </div>
          </div>
          <div class="form__item">
            <p class="form__item-title">Способ оплаты:</p>
            <div class="form__group">
              <div class="form__group-boolean">
                <input class="form__controls-radio" type="radio" name="payment_option" id="id_for_label-1" value="На сайте картой" />
                <label class="form__boolean-label" for="id_for_label-1">На сайте картой</label>
              </div>
              <div class="form__group-boolean">
                <input class="form__controls-radio" type="radio" name="payment_option" id="id_for_label-2" value="Курьером при получении" />
                <label class="form__boolean-label" for="id_for_label-2">Курьером при получении</label>
              </div>
            </div>
          </div>
          <button type="submit" class="form__submit">Оформить заказ</button>
        </div>
        <div class="order-create__col">
          {% load carts_tag %}{% user_carts request as carts %}
          <p class="order-create__info-order"><span>Информация о заказе</span><span>{{ carts.quantity }}</span></p>
          {% for cart in carts %}
          <div class="order-create__item">
            <div class="order-create__thumb">
              {% comment %} {% if cart.product.image %} {% thumbnail cart.product.image "50x50" format="WEBP" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ cart.product.name }}" title="{{ cart.product.name  }}" />
              {% endthumbnail %} {% else %}
              <img src="{% static 'theme/mb/images/no-image.png' %}" alt="{{ cart.product.name }}" title="{{ cart.product.name  }}" />
              {% endif %} {% endcomment %}
            </div>
            <div class="order-create__info">
              <a href="{{ cart.product.get_absolute_url }}" class="order-create__name">{{ cart.product.name }}</a>
              <p class="order-create__price">{{ cart.quantity }} <span>x</span> {{ cart.product.sell_price }} руб.</p>
            </div>
          </div>
          {% endfor %}
          <div class="order-create__promocod">
            <form action="" method="POST" id="promocod-form" class="form">
              <input type="search" name="promocod" id="promocod" class="form__controls" placeholder="Введите промокод" />
            </form>
          </div>
          <div class="order-create__total"><span>Итого:</span> {{ carts.total_price }} руб.</div>
        </div>
      </div>
    </form>
  </section>
</main>
{% endblock %}

main/core/theme/mb/templates/pages/orders/create.html
{% extends "base.html" %} {% load static %} {% load thumbnail %}{% load carts_tag %} {% block content %}
<main>
  <section class="order-create">
    <div class="order-create__container">
      <form action="{% url 'order_create' %}" method="POST" class="form">
        <h2 class="order-create__title _title">Оформление заказа</h2>
        <div class="order-create__row">
          <div class="order-create__col">
            {% csrf_token %}
            <div class="form__item">
              <p class="form__item-title">Ваши контакты</p>
              <div class="form__group-grid">
                <div class="form__group">
                  <label for="id_first_name" class="form__label">Имя*:</label>
                  <input
                    type="text"
                    class="form__controls"
                    id="id_first_name"
                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                    name="first_name"
                    required
                  />
                </div>
                <div class="form__group">
                  <label for="id_email" class="form__label">Email*:</label>
                  <input type="text" class="form__controls" id="id_email" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" required />
                </div>
                <div class="form__group">
                  <label for="id_phone_number" class="form__label">Номер телефона*:</label>
                  <input type="text" class="form__controls" id="id_phone_number" name="phone" value="" placeholder="В формате: XXX-XXX-XX-XX" required />
                </div>
              </div>
            </div>
            <div class="form__item">
              <p class="form__item-title">Адрес доставки</p>
              <div class="form__group-boolean">
                <input type="checkbox" name="pickup" id="pickup" class="form__controls-checkbox" checked />
                <label for="pickup" class="form__boolean-label">Самовывоз</label>
              </div>
              <div class="form__group _hidden" id="id_delivery_address">
                <input type="text" class="form__controls" name="delivery_address" />
                <span class="form__help-text">Город, улица, дом, подъезд, офис/квартира</span>
              </div>
            </div>
            <button type="submit" class="form__submit _btn">Отправить</button>
          </div>
          <div class="order-create__col">
            {% load carts_tag %}{% user_carts request as carts %}
            <p class="order-create__info-order form__item-title"><span>Информация о заказе</span><span> {{ carts.quantity }}</span></p>
            {% for cart in carts %}
            <div class="order-create__item">
              <div class="order-create__thumb">
                {% if cart.product.image %} {% thumbnail cart.product.image "50x50" format="WEBP" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ cart.product.name }}" title="{{ cart.product.name  }}" />
                {% endthumbnail %} {% else %}
                <img src="{% static 'theme/mb/images/no-image.png' %}" alt="{{ cart.product.name }}" title="{{ cart.product.name  }}" />
                {% endif %}
              </div>
              <div class="order-create__info">
                <a href="{{ cart.product.get_absolute_url }}" class="order-create__name">{{ cart.product.name }}</a>
                <p class="order-create__price">{{ cart.quantity }} <span>x</span> {{ cart.product.sell_price }} руб.</p>
              </div>
            </div>
            {% endfor %}
            <div class="order-create__total"><span>Итого:</span> {{ cart.total_price }} руб.</div>
          </div>
        </div>
      </form>
    </div>
  </section>
</main>
{% endblock %}

main/core/theme/mb/templates/pages/orders/error.html
{% extends "base.html" %} {% load static %} {% load carts_tag %} {% block content %}
<main>
  <section class="order-error">
    <h1>Ошибка оформления заказа</h1>
  </section>
</main>
{% endblock %}

main/core/theme/mb/templates/pages/orders/success.html
{% extends "base.html" %} {% load static %} {% block content %}
<main>
  <section class="order-succes">
    <div class="order-succes__container">
      <div class="order-succes__inner">
        <img src="{% static 'theme/mb/images/tick.png' %}" alt="" class="order-succes__image">
        <h1 class="order-succes__title _title">Заказа успешно оформлен</h1>
      </div>
    </div>
  </section>
</main>
{% endblock %}