main/blog/urls.py
from django.urls import path

from blog import views

urlpatterns = [
    path('', views.blog, name="blog"),
    path('<slug:slug>/', views.post, name="post"),
]

main/main/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from .sitemap import PostSitemap, ShopCategory, ShopProduct

sitemaps = {
    'posts': PostSitemap,
    'category': ShopCategory,
    'products': ShopProduct,
}

from main import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('about/', include('home.urls')),
    path('category/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('service/', include('service.urls')),
    path('user/', include('users.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('order.urls')),
    path('admin/', include('admin.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),  # Маршрут для sitemap.xml
    path('', include('home.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/reviews/urls.py
from django.urls import path

from reviews import views


urlpatterns = [
    path('', views.reviews, name="reviews"), 
    path('<slug:slug>/', views.reviews_detail, name="reviews_detail"),
    # path('<slug:slug>/', views.reviews_detail, name="reviews_detail"),
    
]

main/reviews/models.py
from django.db import models
from django.urls import reverse


class Reviews(models.Model):
  avatar = models.ImageField(upload_to="reviews", blank=True, null=True, verbose_name="Аватар пользователя")
  name = models.CharField(max_length=150, blank=True, null=True, verbose_name="Имя")
  slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
  date = models.DateTimeField(blank=True, null=True, verbose_name="Дата")
  text = models.TextField(blank=True, null=True, verbose_name="Текст отзыва")
  status = models.BooleanField(default=False, verbose_name="Статус публикации")
  meta_h1 = models.CharField(max_length=350, null=True, blank=True, verbose_name="Заголовок первого уровня")
  meta_title = models.CharField(max_length=350, null=True, blank=True, verbose_name="Мета заголовок")
  meta_description = models.TextField(null=True, blank=True, verbose_name="Meta описание")
  meta_keywords = models.TextField(null=True, blank=True, verbose_name="Meta keywords")
  
  class Meta:
    db_table = 'reviews' 
    verbose_name = 'Отзыв'
    verbose_name_plural = "Отзывы"
    ordering = ("-id",)
    
  def __str__(self):
    return self.name
  
  def get_absolute_url(self):
        return reverse("reviews_detail", kwargs={"slug": self.slug})

main/reviews/views.py
from django.http import HttpResponse
from django.shortcuts import render

def reviews(request):
  return HttpResponse("Страница отзывов")

def reviews_detail(requset, slug):
  return HttpResponse(f"{slug} - отзыв")

main/core/admin/templates/reviews/admin_reviews.html
{% extends 'admin_base.html' %}



{% block body %}
{% load thumbnail %}

<div class="page__title">Отзывы</div>

<div class="breadcrumb">
    <div class="breadcrumb__inner">

        <ol class="breadcrumb__list">
            <li class="breadcrumb__item"><a class="breadcrumb__link" href="{% url 'admin' %}">Главная</a></li>

            <li class="breadcrumb__item">Отзывы</li>
          
        </ol>


        <a href="{% url 'reviews_add' %}" id="add" class="add">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/></svg>
        </a>
    </div>
</div>




<div class="page search">
    <div class="page__inner search__inner">

        <ul class="responsive-table">
            <li class="table-header">
                
               
                <div class="col col-2">
                  Имя 
                </div>
                <div class="col" style="white-space: normal;flex-basis: 70%;">
                    Текст 
                </div>
                <div class="col col-5">Действие</div>
            </li>

          
            {% for page in admin_reviews %}
            <li class="table-row">
                
                
                
                <div class="col col-2" style="white-space: normal;" data-label="">
                   {{ page.name }}
                   
                </div>
                <div class="col" style="white-space: normal;flex-basis: 70%;" data-label="">
                    {{ page.text }}
                    
                 </div>
                <div class="col col-5" data-label="">
                    
                    <a href="{% url 'reviews_edit' page.id %}" class="edit">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M290.74 93.24l128.02 128.02-277.99 277.99-114.14 12.6C11.35 513.54-1.56 500.62.14 485.34l12.7-114.22 277.9-277.88zm207.2-19.06l-60.11-60.11c-18.75-18.75-49.16-18.75-67.91 0l-56.55 56.55 128.02 128.02 56.55-56.55c18.75-18.76 18.75-49.16 0-67.91z"/></svg>
                    </a>
                    <a href="{% url 'reviews_delete' page.id %}" class="remove">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M268 416h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12zM432 80h-82.41l-34-56.7A48 48 0 0 0 274.41 0H173.59a48 48 0 0 0-41.16 23.3L98.41 80H16A16 16 0 0 0 0 96v16a16 16 0 0 0 16 16h16v336a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128h16a16 16 0 0 0 16-16V96a16 16 0 0 0-16-16zM171.84 50.91A6 6 0 0 1 177 48h94a6 6 0 0 1 5.15 2.91L293.61 80H154.39zM368 464H80V128h288zm-212-48h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12z"/></svg>

                    </a>
                </div>
            </li>
                           
            {% endfor %}          
                            
              
          </ul>
    
    </div>
</div>

{% endblock %}

main/core/admin/templates/reviews/reviews.html
{% extends 'admin_base.html' %}{% load thumbnail %}{% load static %} {% block body %}

<div class="page">
  <div class="page__inner">
    <div class="page__top">
      <h1 class="page__title">Отзывы</h1>
      <ul class="admin-breadcrumbs">
        <li><a href="{% url 'admin' %}">Панель управления</a></li>
        <li>Отзывы</li>
      </ul>
    </div>
    <div class="page__head">
      <div class="page__head-tab">
        <a href="{% url 'admin_reviews_add' %}" class="action-button">Добавить новый</a>
      </div>
    </div>
    <div class="page__content content-page table-top">
      <div class="table">
        <div class="table-header">
          <div class="table-row">
            <div class="table-cell">Аватар</div>
            <div class="table-cell">Имя</div>
            <div class="table-cell">_____</div>
            <div class="table-cell">Действия</div>
          </div>
        </div>
        <div class="table-body">
          {% for item in items %}
          <div class="table-row">
            <div class="table-cell">
              {% if item.avatar %} {% thumbnail item.avatar "50x50" format="WEBP" crop="center" as im %}
              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" />
              {% endthumbnail %} {% else%}
              <img src="{% static 'theme/mb/images/no-image.png' %}" alt="" />
              {% endif %}
            </div>
            <div class="table-cell">{{ item.name }}</div>
            <div class="table-cell" data-label="Header 1"></div>
            <div class="table-cell" data-label="Header 1">
              <a href="{% url 'admin_reviews_edit' item.pk %}">Изменить</a>
              <a href="{% url 'admin_reviews_delete' item.pk %}">Удалить</a>
            </div>
          </div>
          {% endfor %}
          <!-- Add more rows as needed -->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main/core/admin/templates/reviews/reviews_add.html
{% extends 'admin_base.html' %}{% load static %} {% block body %}
<div class="page">
  <div class="page__inner">
    <div class="page__top">
      <h1 class="page__title">Настройки отзыва</h1>
      <ul class="admin-breadcrumbs">
        <li><a href="{% url 'admin' %}">Панель управления</a></li>
        <li><a href="{% url 'admin_product' %}">Отзывы</a></li>
        <li>Настройки отзыва</li>
      </ul>
    </div>
    <form action="." method="POST" class="form" enctype="multipart/form-data">
      <div class="page__head">
        <button type="submit" class="form__btn">
          <img src="{% static 'theme/mb/images/admin/save.svg' %}" alt="" />
          Сохранить
        </button>
      </div>
      {% csrf_token %}
      <div class="page-content _show" id="basic">
        <div class="page-content__row">
          <div class="page-content__col">
            <div class="form__group">
              <label for="{{ form.name.id_for_label }}" class="form__controls-label"> <span>*</span>Имя : </label>
              {{ form.name }} {{ form.name.errors }}
            </div>

            <div class="form__group">
              <label for="{{ form.text.id_for_label }}" class="form__controls-label">Текст отзыва : </label>
              {{ form.text }} {{ form.text.errors }}
            </div>
          </div>
          <div class="page-content__col">
            <div class="form__group">
              <label for="{{ form.slug.id_for_label }}" class="form__controls-label">
                <span>*</span>
                URL :
              </label>
              {{ form.slug }} {{ form.slug.errors }}
            </div>
            <div class="form__group form__group-image">
              <label for="{{ form.avatar.id_for_label }}" class="form__controls-label">Аватар :</label>
              {{ form.avatar }} {{ form.avatar.errors }}
            </div>
            {% comment %}
            <div class="form__group">
              <label for="{{ form.date.id_for_label }}" class="form__controls-label">Дата создания :</label>
              {{ form.date }} {{ form.date.errors }}
            </div>
            {% endcomment %}

            <div class="form__group-checkbox">
              {{ form.status }} {{ form.status.errors }}
              <label for="{{ form.status.id_for_label }}" class="form__controls-label"> Опубликовать ? :</label>
            </div>
          </div>
        </div>
      </div>
      <div class="page-content" id="seo">
        <!-- SEO страницы -->
        <div class="page-content__row">
          <div class="page-content__onecol">
            <div class="form__group">
              <label for="{{ form.meta_h1.id_for_label }}" class="form__controls-label"> Заголовок h1 : </label>
              {{ form.meta_h1 }} {{ form.meta_h1.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_title.id_for_label }}" class="form__controls-label"> Мета заголовок : </label>
              {{ form.meta_title }} {{ form.meta_title.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_description.id_for_label }}" class="form__controls-label">
                Мета описание :
                <div class="meta-lenght">0</div>
              </label>
              {{ form.meta_description }} {{ form.meta_description.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_description.id_for_label }}" class="form__controls-label"> Мета keywords : </label>
              {{ form.meta_keywords }} {{ form.meta_keywords.errors }}
            </div>
          </div>
        </div>
      </div>
      <div class="page-content" id="char">
        <!-- Характеристики товара страницы -->
        <div class="page-content__row">
          <div class="page-content__onecol">
            <div class="page-content__char" id="paste-char">
              {% for char in chars %}
              <div class="form__group-char">
                <input type="text" name="old_char_id" value="{{ char.id }}" hidden />
                <label for="{{ form.category.id_for_label }}" class="form__controls-label">Название характеристики :</label>
                <select name="old_text_name" class="form__controls" placeholder="Название характеристики" id="id_name">
                  <option value="{{ char.char_name.id }}">{{ char.char_name.text_name }}</option>
                  {% for ch in all_chars %}
                  <option value="{{ ch.id }}">{{ ch.text_name }}</option>
                  {% endfor %}
                </select>
                <label for="id_char_value" class="form__controls-label">Значение :</label>
                <input type="text" name="old_char_value" class="form__controls" placeholder="Значение" required="" id="id_char_value" value="{{ char.char_value }}" />
                <a href="" class="form__remove"> Удалить </a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <button type="button" id="add-char" class="form__plus">Добавить характеристику</button>
      </div>
    </form>
    <div class="select-hide" id="select-hide" style="opacity: 0; position: absolute">{{ option_form.type }} {{ product_char_form.char_name }}</div>
  </div>
</div>

{% endblock %}

main/core/admin/templates/reviews/reviews_edit.html
{% extends 'admin_base.html' %}{% load static %} {% block body %}
<div class="page">
  <div class="page__inner">
    <div class="page__top">
      <h1 class="page__title">Настройки отзыва</h1>
      <ul class="admin-breadcrumbs">
        <li><a href="{% url 'admin' %}">Панель управления</a></li>
        <li><a href="{% url 'admin_product' %}">Отзывы</a></li>
        <li>Настройки отзыва</li>
      </ul>
    </div>
    <form action="." method="POST" class="form" enctype="multipart/form-data">
      <div class="page__head">
        <div class="page__head-tab">
          <button type="button" data-name="basic" class="page__head-btn _active">Основные</button>
          <button type="button" data-name="seo" class="page__head-btn">Поля SEO</button>
        </div>
        <button type="submit" class="form__btn">
          <img src="{% static 'theme/mb/images/admin/save.svg' %}" alt="" />
          Сохранить
        </button>
      </div>
      {% csrf_token %}
      <div class="page-content _show" id="basic">
        <div class="page-content__row">
          <div class="page-content__col">
            <div class="form__group">
              <label for="{{ form.name.id_for_label }}" class="form__controls-label"> <span>*</span>Имя : </label>
              {{ form.name }} {{ form.name.errors }}
            </div>

            <div class="form__group">
              <label for="{{ form.text.id_for_label }}" class="form__controls-label">Текст отзыва : </label>
              {{ form.text }} {{ form.text.errors }}
            </div>
          </div>
          <div class="page-content__col">
            <div class="form__group">
              <label for="{{ form.slug.id_for_label }}" class="form__controls-label">
                <span>*</span>
                URL :
              </label>
              {{ form.slug }} {{ form.slug.errors }}
            </div>
            <div class="form__group form__group-image">
              <label for="{{ form.avatar.id_for_label }}" class="form__controls-label">Аватар :</label>
              {{ form.avatar }} {{ form.avatar.errors }}
            </div>
            {% comment %}
            <div class="form__group">
              <label for="{{ form.date.id_for_label }}" class="form__controls-label">Дата создания :</label>
              {{ form.date }} {{ form.date.errors }}
            </div>
            {% endcomment %}

            <div class="form__group-checkbox">
              {{ form.status }} {{ form.status.errors }}
              <label for="{{ form.status.id_for_label }}" class="form__controls-label"> Опубликовать ? :</label>
            </div>
          </div>
        </div>
      </div>
      <div class="page-content" id="seo">
        <!-- SEO страницы -->
        <div class="page-content__row">
          <div class="page-content__onecol">
            <div class="form__group">
              <label for="{{ form.meta_h1.id_for_label }}" class="form__controls-label"> Заголовок h1 : </label>
              {{ form.meta_h1 }} {{ form.meta_h1.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_title.id_for_label }}" class="form__controls-label"> Мета заголовок : </label>
              {{ form.meta_title }} {{ form.meta_title.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_description.id_for_label }}" class="form__controls-label">
                Мета описание :
                <div class="meta-lenght">0</div>
              </label>
              {{ form.meta_description }} {{ form.meta_description.errors }}
            </div>
            <div class="form__group">
              <label for="{{ form.meta_description.id_for_label }}" class="form__controls-label"> Мета keywords : </label>
              {{ form.meta_keywords }} {{ form.meta_keywords.errors }}
            </div>
          </div>
        </div>
      </div>
      <div class="page-content" id="char">
        <!-- Характеристики товара страницы -->
        <div class="page-content__row">
          <div class="page-content__onecol">
            <div class="page-content__char" id="paste-char">
              {% for char in chars %}
              <div class="form__group-char">
                <input type="text" name="old_char_id" value="{{ char.id }}" hidden />
                <label for="{{ form.category.id_for_label }}" class="form__controls-label">Название характеристики :</label>
                <select name="old_text_name" class="form__controls" placeholder="Название характеристики" id="id_name">
                  <option value="{{ char.char_name.id }}">{{ char.char_name.text_name }}</option>
                  {% for ch in all_chars %}
                  <option value="{{ ch.id }}">{{ ch.text_name }}</option>
                  {% endfor %}
                </select>
                <label for="id_char_value" class="form__controls-label">Значение :</label>
                <input type="text" name="old_char_value" class="form__controls" placeholder="Значение" required="" id="id_char_value" value="{{ char.char_value }}" />
                <a href="" class="form__remove"> Удалить </a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <button type="button" id="add-char" class="form__plus">Добавить характеристику</button>
      </div>
    </form>
    <div class="select-hide" id="select-hide" style="opacity: 0; position: absolute">{{ option_form.type }} {{ product_char_form.char_name }}</div>
  </div>
</div>

{% endblock %}